insert into public.skills (name, category) values
  ('Python','Software & Data'),
  ('SQL','Software & Data'),
  ('Java','Software & Data'),
  ('JavaScript','Software & Data'),
  ('TypeScript','Software & Data'),
  ('Git','Software & Data'),
  ('Docker','Software & Data'),
  ('Kubernetes','Software & Data'),
  ('REST APIs','Software & Data'),
  ('Data Visualization','Software & Data'),
  ('Statistics','Software & Data'),
  ('Machine Learning','Software & Data'),
  ('PyTorch','Software & Data'),
  ('TensorFlow','Software & Data'),
  ('MLOps','Software & Data'),
  ('dbt','Software & Data'),
  ('Data Engineering','Software & Data'),
  ('Cloud (AWS)','Software & Data'),
  ('Analytics','Software & Data'),
  ('Figma','Design'),
  ('User Research','Design'),
  ('Prototyping','Design'),
  ('Design Systems','Design'),
  ('Wireframing','Design'),
  ('Interaction Design','Design'),
  ('Project Management','Product & PM'),
  ('Product Management','Product & PM'),
  ('Agile','Product & PM'),
  ('Roadmapping','Product & PM'),
  ('Process Improvement','Product & PM'),
  ('SEO','Marketing & Growth'),
  ('A/B Testing','Marketing & Growth'),
  ('Copywriting','Marketing & Growth'),
  ('Content Marketing','Marketing & Growth'),
  ('Social Media','Marketing & Growth'),
  ('Email Marketing','Marketing & Growth'),
  ('Growth Experimentation','Marketing & Growth'),
  ('Excel','Business & Ops'),
  ('Financial Modeling','Business & Ops'),
  ('Operations','Business & Ops'),
  ('Customer Support','Business & Ops'),
  ('Sales','Business & Ops'),
  ('Communication','Communication'),
  ('Presentation','Communication'),
  ('Technical Writing','Communication'),
  ('Collaboration','Communication'),
  ('Stakeholder Management','Communication')
on conflict (name) do nothing;
